version: '3.11'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=car_scraper.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1

  celery_worker:
    build: .
    command: celery -A car_scraper worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=car_scraper.settings

  celery_beat:
    build: .
    command: celery -A car_scraper beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=car_scraper.settings

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"