# Generated by Django 5.1.3 on 2024-11-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, unique=True)),
                ('car_brand_name', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=200)),
                ('car_year', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=50)),
                ('body_color', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.car')),
            ],
        ),
    ]
